name: RedeWay
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Rede-Way RPG

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v2

      - uses: retypeapp/action-github-pages@v2
        with:
          update-branch: true
